"""Build the `Knight of Xoroth [CoA]` WeakAura pack for Ascension Conquest of Azeroth.

Written as CONTENT over the shared engine -- the build_chronomancer.py shape,
no convergence flags. Layout follows notes/layout-standard.md.

        [ alerts: NO PESTILENCE / NO PET / NO OATH ]  <- per spec, active-only
        [ on TARGET: your DoTs / debuffs ]            <- band 2, active-only
        [ on me: procs, running CDs, buffs ]          <- band 3, active-only
              [  MAIN ROW - flush         ]           <- band 4
              [  resource envelope        ]           <- band 5, fixed height
              [ offensive cooldowns       ]           <- band 6, wraps at 9
              [ defensive + utility       ]           <- band 7, wraps at 9
              [ long-term buffs           ]           <- band 8, active-only

Class shape (notes/requirements-knight-of-xoroth.md):

  * THE DEMONFIRE ECONOMY. Every spec builds Demonfire (aura 500906,
    "Consumed to empower abilities. Stacks 6 times") with its fillers and
    dumps it into scaling spenders. The envelope renders a 6-cell stack_bar,
    the rage bar under it, and Demon's Blood (800999, stacks to 10 -- the
    Black Shield / Juggernaut fuel) as a thin minor bar -- three bands in the
    fixed envelope, the Stormbringer-maelstrom heights. Identical on every
    spec, so no height variance.

  * TRANSFORM MAIN ROWS. Three talents replace a button outright ("Transforms
    your X into Y" -- Sidekick talent text, quoted in requirements sec2):
    Sever -> Brimstone Bludgeon and Flames of Xoroth -> Warbringer on war,
    Infernal Strike -> Shieldgore on defiance. This fork resolves no spell
    overrides, so each spec's main row tracks the REPLACEMENT's own id
    directly -- the Stormbringer Tempest Sovereign precedent, with the
    build-defining assumption declared in the requirements doc. The two
    choose-one defiance nodes (Hellfire Bellows; Impcaller, which removes
    Call: Hellfire Imp) get a native ["Spell Known"] gate trigger instead, so
    an untalented character sees no dead button.

  * THE PET SPEC IS HELLFIRE. A permanent Greater Imp (Summon: Greater Imp
    520661, granted by the tree node 92101). NO PET alert asks the PET unit
    for Greater Imp Scaling (520662) and gates on knowing the summon -- the
    Stormbringer/Tinker shape. Doom (802602) is a player button transforming
    the pet into a Doomguard; its window rides the buff row with unit="pet".
    Defiance's Hellfire Imps are 30s cooldown-length summons regenerated by
    the rotation -- no alert, no count (requirements sec6.4). The Imp's OWN
    spellbook (Burst, Burning Slap, Burning Mischief, the Lesser Pestilences)
    is `ignore` per the Chronobuff precedent.

  * PESTILENCES ARE STANCES. War and hellfire each keep one emanating
    (Sidekick: "Keep Pestilence of Death active before every pull" / "Keep
    Pestilence of Apocalypse up almost constantly"), so each gets a
    NO PESTILENCE alert firing when none of the five stance auras is up.
    Defiance's analog is Oath of Defiance (804285), the tank stance -> the
    NO OATH alert. All three alerts gate on knowing the spec's stance.

  * DEFIANCE TANKS (spec-roles.md, Sidekick-sourced). Nothing structural
    changes: its main row is the cited tanking loop, Snarl (the taunt) rides
    the utility row -- the felsworn-tyrant precedent.

WA_GLOW=1 additionally glows main-row icons the moment they come off cooldown.
"""
import wapack as W

# Release tag. Feeds the uid salt. WeakAuras dedupes imports on uid, so a
# rebuilt pack MUST carry a different salt or the client treats it as
# already-installed and silently keeps the old copy. Bump on any release.
#
# 0.1: first build (draft bar, notes/production-run.md). Roles were assigned by
# an automated pass and cleared in bulk 2026-08-07 -- provenance in the
# buildlog; the hedged rows are listed in requirements sec6.
VERSION = "0.1"

# Only real Ascension/3.3.5 icon names -- a missing texture renders as a "?".
FALLBACK = {}
# ONLY deliberate choices belong here: an entry overrides the CLIENT's own art.
#
# Forgefiend's Bulwark and Juggernaut both resolve to
# epic_rpg_icon_pack_fire_0004s_0000_armor_border upstream and can sit side by
# side in the merged Buffs row -- the collision the duplicate-art check exists
# to catch. Forgefiend's Bulwark borrows Infernal Bulwark's shield art
# (inv_shield_firelandsraid_d_01): a passive (role ignore) that never renders
# in any row, so the fix cannot introduce a fresh clash, and it literally
# depicts a fiery shield -- the block-enrage the aura is.
OVERRIDE = {"Forgefiend's Bulwark": "inv_shield_firelandsraid_d_01"}

# Not tooltip-verified, but read off db.ascension.gg tooltips where the digest
# linked a COMPONENT rather than the castable, or had no row at all. Each
# replacement's tooltip was read and matches the skillbook text
# (requirements sec0).
CROSSCHECK = {
    # digest 680815 is rank "Heal" -- the Demonfire-spent heal component.
    # 802345 carries the castable stance tooltip ("Emanate a pestilence,
    # causing each Demonfire spent to heal for 1% of your maximum health",
    # 4 sec cooldown). 802604 is the PET's copy (rank "Pet").
    "Pestilence of War": 802345,
    # digest 704467 is rank "Damage". 804786 carries the stance tooltip
    # ("Emanate the Pestilence of Apocalypse ... 10% increased Fire damage").
    # 806962 is the PET's copy.
    "Pestilence of Apocalypse": 804786,
    # digest 706752 is rank "Force" (706753 is the "Heal" half). 805677
    # carries the full player tooltip: 1 min cooldown, sacrifice imps, heal,
    # leave corpses.
    "Sacrificial Circle": 805677,
    # 573453 is a "Shapeshift Holder"; 800999 is the stacking player buff
    # ("increasing healing received ... stacking up to 10 times") and 804345
    # the granting passive. The buff is what the bar reads.
    "Demon's Blood": 800999,
    # not in the digest at all; talent text "grants a stack of Gorged for 30
    # seconds" and db.ascension name search resolve it to 681205.
    "Gorged": 681205,
}

# Identity, data and the entire build vocabulary come from wapack. init() runs
# BEFORE the star import because it is what gives the unqualified names below
# their values. No convergence flags: this class starts on every default.
#
# CD_PER_ROW derives from the NARROWEST main row. All three specs render five
# main icons: row_w(5) = 228px and 28w - 2 <= 1.2 * 228 allows w <= 9.8 -> 9.
# 9 keeps hellfire's 8 offensive cooldowns on a single row.
CLS = W.init("knight-of-xoroth", version=VERSION, prefix="KX", cd_per_row=9,
             override=OVERRIDE, fallback=FALLBACK, crosscheck=CROSSCHECK)

from wapack import *          # noqa: E402,F401,F403  -- deliberate, see above

# ---- the resource system ---------------------------------------------------
# Ids and stack counts from db.ascension tooltips (requirements sec1/sec6.1-2).
DEMONFIRE = 500906            # "Consumed to empower abilities. Stacks 6 times."
DEMONFIRE_CELLS = 6           # Demon Heart grants 6; Rain of Chaos keys off 6
DEMONS_BLOOD = 800999         # "stacking up to 10 times" (Heart of Xoroth +N)
BLOOD_CELLS = 10

# Abilities that hold charges rather than a plain cooldown, from tooltips:
# "2 Charges, 8 sec recharge" (Gore), "2 Charges, 60 sec recharge"
# (Hellbound Charge).
CHARGES = {"Gore": 2, "Hellbound Charge": 2}

# When one of these buffs is up, the ABILITY it empowers glows -- the cue the
# cooldown swipe cannot give. All from talent text (requirements sec1):
#   Decimation      "Your next Skulltaker or Warbringer is guaranteed to
#                   critically strike" (30s window, war)
#   Goredrenched    Gore-empowerment window Merciless can preserve (war)
#   Xorothian Rage  "your next Infernal Strike ... guaranteed to critically
#                   strike" (hellfire, from Skulltaker at 6 Demonfire)
#   Infernal Steel  "your next Hellmaw ... tick -25% faster and cost -50%
#                   less Rage" (hellfire)
#   Ritual Fire     6s window ON THE TARGET during which Shieldgore applies
#                   Black Shield (defiance) -- a target-unit group, the
#                   Runemaster Marked-target shape.
PROC_GLOW = {
    "Skulltaker": ["Decimation"],
    "Warbringer": ["Decimation"],
    "Gore": ["Goredrenched"],
    "Infernal Strike": ["Xorothian Rage"],
    "Hellmaw": ["Infernal Steel"],
    "Shieldgore": [{"names": ["Ritual Fire"], "unit": "target",
                    "helpful": False}],
}
PROC_STACKS = set()

# Offense-row abilities that apply no self-buff worth a second icon in the
# "on me" row: instants, ground effects and target debuffs (the debuffs join
# the target band instead).
NO_BUFF = {
    "Demon Heart", "Unleash Pestilence", "Hellstorm", "Melt", "Unseal",
    "Curse of Hel'nurath", "Curse of Xoroth", "Call: Hellfire Abyssal",
}

# Displays whose extra trigger is a GATE, not an alternative sighting: they
# must keep `disjunctive` at its "all" default. See apply_leaf_gates().
NEEDS_ALL = set()

W.configure(charges=CHARGES, proc_glow=PROC_GLOW, proc_stacks=PROC_STACKS,
            no_buff=NO_BUFF)


# ================================================================== 1. CORE
# Every alert here is spec-shaped (each spec has its own stance and only
# hellfire has a pet), so Core carries nothing class-wide -- the Stormbringer
# shape. The group still exists so the pack keeps the standard skeleton.
CORE = []
add(B.group("KX Core", ROOT, CORE, x=0, y=0))


# The five Pestilence stances. Mutually exclusive in practice (one active
# Pestilence -- "Changing your active Pestilence..." in Brimstone
# Battlemaster's text); the alert only needs "at least one", so it is correct
# under both readings (requirements sec6.10). Ids are the CASTABLE stances --
# the digest components are corrected in CROSSCHECK above.
PESTILENCES = [
    ("Pestilence of War", 802345),
    ("Pestilence of Death", 801054),
    ("Pestilence of Conquest", 801053),
    ("Pestilence of Apocalypse", 804786),
    ("Pestilence of Famine", 802344),
]
OATH = 804285                 # Oath of Defiance -- the tank stance


def stance_alert(spec_name, label, auras, gate_id, art, bands, extra=()):
    """A missing-stance alert: fires when NONE of `auras` is up AND the spec's
    stance spell is known -- so a levelling character who cannot take a stance
    yet is not nagged. The Stormbringer NO AEGIS shape."""
    band = f"KX {spec_name} Alerts"
    keys = [str(i) for _n, i in auras] + [n for n, _i in auras]
    d = B.icon(
        f"{band} {label.title()}", band,
        [B.aura_trigger(keys, own_only=False, show_on="showOnMissing"),
         B.spell_known_trigger(gate_id, exact=False)],
        ic(art), size=SZ_ALERT, desaturate=True,
        subregions=[B.sub_background(),
                    B.sub_text(label, size=10, anchor="INNER_BOTTOM",
                               color=(1, 0.35, 0.35, 1)),
                    B.sub_border(color=(1, 0.2, 0.2, 1), size=2, offset=1,
                                 edge=EDGE),
                    B.sub_glow(True, "buttonOverlay", (1, 0.3, 0.3, 1))])
    NEEDS_ALL.add(d["id"])       # missing-aura AND spell-known, never "any"
    out = [add(d)] + list(extra)
    add(B.dynamicgroup(band, f"KX {spec_name}", out, x=0, y=Y_ALERT,
                       grow="HORIZONTAL", space=6))
    bands.append(band)


# ---- long-term buffs -------------------------------------------------------
# DATA, not displays: the band is emitted once per spec by longterm_band(),
# anchored under that spec's own utility row, and reads the inventory. Two
# families:
#   Pestilences / Oath   the stance actually emanating (active-only, so the
#                        row shows which one, and the alert covers absence)
#   Marks                the Four Horsemen ally stat marks -- the blessing
#                        shape, checked once per pull.
LONGTERM_COL = {
    "Pestilence": (0.75, 0.45, 0.95),
    "Mark": (0.55, 0.75, 1.00),
    "Oath": (0.95, 0.70, 0.30),
}
_LONGTERM_DEFAULT_COL = (0.95, 0.85, 0.45)


def _family_col(name):
    for key, col in LONGTERM_COL.items():
        if key.lower() in name.lower():
            return col
    return _LONGTERM_DEFAULT_COL


def longterm_for(spec_key):
    """Every `longterm` inventory row this spec can actually cast."""
    return sorted(n for n, a in ABILITIES.items()
                  if a["default"] == "longterm" and a["id"]
                  and (a["specs"] is None or spec_key in a["specs"]))


def longterm_band(spec_name, spec_key, bands, y):
    """The long-term row for ONE spec, anchored under its own cooldown stack.

    The gate comes free: the merge tags any leaf whose parent chain reaches
    `KX <Spec>` with that spec, and apply_leaf_gates puts the spec's signature
    spell on it (L8 / L17 / trainer -- see SPEC_KNOWN).
    """
    band = f"KX {spec_name} Longterm"
    out = []
    for name in longterm_for(spec_key):
        col = _family_col(name)
        sid_ = ABILITIES[name]["id"]
        out.append(add(B.icon(
            f"KX {spec_name} Longterm {name}", band,
            # By id AND name: the Marks come in plain and Greater pairs whose
            # names are prefixes of each other; an id match settles it.
            [B.aura_trigger([str(sid_), name], own_only=False)],
            ic(name), size=SZ_SMALL,
            subregions=[B.sub_text("%p", size=9, anchor="INNER_BOTTOM",
                                   color=col + (1.0,)),
                        thin()])))
    if not out:
        return
    add(B.dynamicgroup(band, f"KX {spec_name}", out, x=0, y=y - LONG_GAP,
                       grow="HORIZONTAL", space=GAP))
    bands.append(band)


# Class-wide short buffs, merged per spec into that spec's "what is up right
# now" row. All active-only.
#   Suffuse       the running self-heal + DR window (per-DF duration)
#   Black Shield  the Demon's Blood absorb while it holds
#   Juggernaut    the DR + tick-heal window
#   Burning Rage  the CC-immune enrage window
SHORT_ENTRIES = [
    ("Suffuse", (0.55, 0.95, 0.55), {}),
    ("Black Shield", (0.60, 0.85, 1.00), {}),
    ("Juggernaut", (0.80, 0.70, 0.50), {}),
    ("Burning Rage", (1.00, 0.55, 0.20), {}),
]


def envelope(spec_name, bands):
    """Demonfire + rage + Demon's Blood. Identical on all three specs, three
    bands in the fixed-height envelope (~-156..-186) -- the Stormbringer
    maelstrom heights, so every anchor below is unchanged.

    Demonfire sits NEAREST the main row because the spend decision is the
    thing the rotation is played around (every spec's Resource paragraph);
    rage underneath; Demon's Blood is the thin minor meter -- background AND
    independent (it feeds Black Shield / Juggernaut when SPENT), so `minor`
    rather than `fused`.
    """
    w = row_w(5)
    W.stack_bar(f"KX {spec_name} Demonfire", f"KX {spec_name}", DEMONFIRE,
                DEMONFIRE_CELLS, (1.00, 0.55, 0.20), -160,
                B.health_trigger("player"), w, bands, h=10)
    bands.append(rage_bar(f"KX {spec_name} Rage", f"KX {spec_name}", -171, w))
    W.stack_bar(f"KX {spec_name} Blood", f"KX {spec_name}", DEMONS_BLOOD,
                BLOOD_CELLS, (0.75, 0.20, 0.25), -182,
                B.health_trigger("player"), w, bands, h=8)


def rage_bar(gid, parent, y, w):
    """Rage is power type 1 on a 3.3.5 client. mana_bar hardcodes 0, so this
    is the same aurabar with the right powertype -- the one class-content
    divergence the resource envelope needs."""
    add(B.aurabar(gid, parent, [B.power_trigger("player", 1)],
                  x=0, y=y, w=w, h=10,
                  color=(0.85, 0.25, 0.25, 1.0),
                  subregions=[
                      B.sub_text("%p", size=9, anchor="INNER_RIGHT", x=-4,
                                 justify="RIGHT"),
                  ]))
    return gid


def known_gate(d, spell_id):
    """AND a native ["Spell Known"] trigger onto a display, so it only renders
    while `spell_id` is known.

    For the choose-one defiance talents: Hellfire Bellows exists only when its
    node is taken, and Impcaller REMOVES Call: Hellfire Imp (a 3.3.5 server
    changes a button by granting the new spell and taking the base away, and
    this fork resolves no overrides). The load-side spec gate cannot express
    this -- load.spellknown holds ONE id and assert_gated requires the spec
    signature on single-spec leaves -- so the gate rides the trigger list,
    with NEEDS_ALL keeping `disjunctive` at "all".

    Only legal on a display with no PROC_GLOW triggers: under "all" a proc
    trigger would become a second gate and hide the button until it procs.
    """
    trs = triggers_of(d)
    assert len(trs) == 1, f"known_gate on {d['id']}: expected 1 trigger"
    trs.append(B.spell_known_trigger(spell_id))
    d["triggers"] = B._trigger_wrap(trs)
    d["triggers"].pop("disjunctive", None)
    NEEDS_ALL.add(d["id"])
    return d


# ===================================================================== 2. WAR
# Str/AP melee bruiser. Row order is the ROTATION, from the cited Sidekick
# text: "Open hard pulls with Brimstone Bludgeon ... build Demonfire with Gore
# ... and Meatsaw ... Dump stacked Demonfire into Skulltaker ... Weave
# Brimstone Bludgeon on cooldown", with Warbringer ("adds one more AoE slam",
# Decimation's second target) closing the row. Brimstone Bludgeon and
# Warbringer are the talent transforms of Sever / Flames of Xoroth, tracked on
# their own ids -- requirements sec2, assumption declared there.
WR = []
stance_alert("War", "NO PESTILENCE",
             PESTILENCES, 801054, "Pestilence of Death", WR)
WR.append(cd_group("KX War Main", "KX War",
                   ["Brimstone Bludgeon", "Gore", "Meatsaw", "Skulltaker",
                    "Warbringer"],
                   y=Y_MAIN, size=SZ_MAIN, glow=GLOW, text_size=14,
                   spec="war"))
envelope("War", WR)
# Your bleed on the target: Torn Flesh, applied by Meatsaw. Applied-by aura,
# so match by name as well (the dot_bars by_name path).
WR.append(dot_bars("KX War Target", "KX War",
                   [("Torn Flesh", (0.90, 0.35, 0.35), {"by_name": True})],
                   y=Y_TARGET, refresh_at=4))
_y_W = emit_bottom_block("War", "war", WR,
                         [("Decimation", (1.00, 0.85, 0.40)),
                          ("Goredrenched", (0.95, 0.45, 0.45)),
                          ("Gorged", (0.75, 0.25, 0.30)),
                          ("Demonic Frenzy", (0.95, 0.60, 0.30)),
                          ("The Butcher", (0.80, 0.70, 0.50)),
                          ("Burning Blade", (1.00, 0.55, 0.20)),
                          ("Hellknight", (0.95, 0.85, 0.45))],
                         SHORT_ENTRIES)
longterm_band("War", "war", WR, _y_W)
add(spec_group("KX War", WR))


# ================================================================ 3. HELLFIRE
# THE PET SPEC: melee/caster hybrid around a permanent Greater Imp. Row order
# is the cited numbered rotation: Infernal Strike engage/filler (2 Demonfire)
# -> Seeking Flame (builder + slow) -> Hellmaw (the big Shadowflame dump) ->
# Flames of Xoroth (the AoE dump) -> Skulltaker (the crit finisher whose
# 6-stack cast arms Xorothian Rage / Infernal Steel).
HF = []

# NO PET: trigger 1 asks the PET unit for the Greater Imp's scaling aura and
# fires on absence; trigger 2 gates on knowing the summon at all, so a
# character who cannot summon yet is not nagged. Whether an absent pet unit
# reports "missing" (vs never firing) is the same unverified mechanism
# Stormbringer and Tinker deferred -- requirements sec6.6.
_no_pet = B.icon(
    "KX Hellfire Alerts No Pet", "KX Hellfire Alerts",
    [B.aura_trigger(["520662", "Greater Imp Scaling"], unit="pet",
                    own_only=False, show_on="showOnMissing"),
     B.spell_known_trigger(sid("Summon: Greater Imp"))],
    ic("Summon: Greater Imp"), size=SZ_ALERT, desaturate=True,
    subregions=[B.sub_background(),
                B.sub_text("NO PET", size=10, anchor="INNER_BOTTOM",
                           color=(1, 0.35, 0.35, 1)),
                B.sub_border(color=(1, 0.2, 0.2, 1), size=2, offset=1,
                             edge=EDGE),
                B.sub_glow(True, "buttonOverlay", (1, 0.3, 0.3, 1))])
NEEDS_ALL.add(_no_pet["id"])
stance_alert("Hellfire", "NO PESTILENCE",
             PESTILENCES, 804786, "Pestilence of Apocalypse", HF,
             extra=[add(_no_pet)])
HF.append(cd_group("KX Hellfire Main", "KX Hellfire",
                   ["Infernal Strike", "Seeking Flame", "Hellmaw",
                    "Flames of Xoroth", "Skulltaker"],
                   y=Y_MAIN, size=SZ_MAIN, glow=GLOW, text_size=14,
                   spec="hellfire"))
envelope("Hellfire", HF)
# The spec's maintained enemy state: Melt's armor shred, Hellmaw's burn, the
# Hel'nurath curse. All applied by pressed buttons in the offense/main rows.
HF.append(dot_bars("KX Hellfire Target", "KX Hellfire",
                   [("Melt", (0.95, 0.60, 0.30), {}),
                    ("Hellmaw", (0.75, 0.35, 0.95), {}),
                    ("Curse of Hel'nurath", (0.90, 0.35, 0.35),
                     {"by_name": True})],
                   y=Y_TARGET, refresh_at=4))
_y_H = emit_bottom_block("Hellfire", "hellfire", HF,
                         [("Hellfire Form", (1.00, 0.55, 0.20)),
                          ("Xorothian Fury", (1.00, 0.85, 0.40)),
                          ("Xorothian Rage", (1.00, 0.45, 0.30)),
                          ("Infernal Steel", (0.80, 0.70, 0.50)),
                          ("Flamewrath", (0.95, 0.70, 0.45)),
                          # the Doomguard window lives on the PET
                          ("Doom", (0.75, 0.35, 0.95), {"unit": "pet"})],
                         SHORT_ENTRIES)
longterm_band("Hellfire", "hellfire", HF, _y_H)
add(spec_group("KX Hellfire", HF))


# ================================================================ 4. DEFIANCE
# THE TANK. Row order is the cited rotation: "Shieldgore on cooldown (main
# threat/damage + 2 Demonfire), Call: Hellfire Imp on cooldown ... Dump
# Demonfire into Suffuse liberally ... Implosion on pulls ... Hellfire Bellows
# against packs". Shieldgore is the Infernal Strike transform (own id);
# Bellows and Call: Hellfire Imp carry Spell Known gate triggers because their
# nodes are choose-one / removable -- see known_gate().
DF = []
stance_alert("Defiance", "NO OATH",
             [("Oath of Defiance", OATH)], OATH, "Oath of Defiance", DF)

_df_main = []
for _n in ("Shieldgore", "Call: Hellfire Imp", "Suffuse", "Implosion",
           "Hellfire Bellows"):
    _d = cd_icon(f"KX Defiance Main {_n}", "KX Defiance Main", _n, SZ_MAIN,
                 spec="defiance")
    if _n == "Call: Hellfire Imp":
        known_gate(_d, sid("Call: Hellfire Imp"))     # Impcaller removes it
    elif _n == "Hellfire Bellows":
        known_gate(_d, sid("Hellfire Bellows"))       # choose-one TE node
    _df_main.append(add(_d))
add(B.dynamicgroup("KX Defiance Main", "KX Defiance", _df_main, x=0, y=Y_MAIN,
                   grow="HORIZONTAL", space=GAP))
DF.append("KX Defiance Main")
envelope("Defiance", DF)
# The tank's maintained target state: the priming curse, its Ritual Fire
# window (which also glows Shieldgore), and the Torn Flesh bleed.
DF.append(dot_bars("KX Defiance Target", "KX Defiance",
                   [("Curse of Xoroth", (0.75, 0.35, 0.95), {"by_name": True}),
                    ("Ritual Fire", (1.00, 0.55, 0.20), {}),
                    ("Torn Flesh", (0.90, 0.35, 0.35), {"by_name": True})],
                   y=Y_TARGET, refresh_at=4))
_y_D = emit_bottom_block("Defiance", "defiance", DF,
                         [("Forgefiend's Bulwark", (0.95, 0.60, 0.30)),
                          ("Soul Furnace", (0.60, 0.85, 1.00)),
                          ("Hellwrath", (0.75, 0.25, 0.30)),
                          ("Hellrider", (0.95, 0.85, 0.45)),
                          ("Legion's Presence", (0.75, 0.35, 0.95))],
                         SHORT_ENTRIES)
longterm_band("Defiance", "defiance", DF, _y_D)
add(spec_group("KX Defiance", DF))


W.configure(merge_bands=MERGE_BANDS)
merge_bands()

# One spell unique to each spec, for load.use_spellknown. Picked as the LOWEST
# gateable spec-unique id -- gateable meaning spell-meta says IsSpellKnown can
# be trusted with it, which rules out every ranked spell (Sever, Gore,
# Shieldgore, Infernal Strike are all Rank 1 rows) and every component.
SPEC_KNOWN = {
    "War": 801042,        # Flay Corpse, L8, war-only, unranked
    "Hellfire": 805664,   # Unseal, L17, hellfire-only, unranked
    "Defiance": 706756,   # Chains of Xoroth, defiance-only, unranked
}
W.configure(needs_all=NEEDS_ALL, spec_known=SPEC_KNOWN)

_GATED, _ANY, _CLASSED = apply_leaf_gates()
assert_gated()

W.chain_ladder()
W.settle_icon_source()
if SPEC_ONLY:
    restrict_to_spec()


if __name__ == "__main__":
    W.finish((_GATED, _ANY, _CLASSED))
